# Generated by Django 3.1.1 on 2020-09-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200916_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
